use std::net::SocketAddr;
use std::time::Duration;
use tokio::time::sleep;

use rlightning::networking::client::Client;
use rlightning::networking::resp::RespValue;
use rlightning::networking::server::Server;
use rlightning::storage::engine::{StorageConfig, StorageEngine};

/// Tests Redis Streams functionality
/// Streams are an append-only data structure for message streaming
#[tokio::test]
async fn test_redis_streams() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    // Set up server with a unique port
    let addr: SocketAddr = "127.0.0.1:16397".parse()?;
    let config = StorageConfig::default();
    let storage = StorageEngine::new(config);

    let server = Server::new(addr, storage);

    // Start server in background
    tokio::spawn(async move {
        if let Err(e) = server.start().await {
            eprintln!("Server error: {:?}", e);
        }
    });

    // Wait for server to start
    sleep(Duration::from_millis(200)).await;

    // Connect client
    let mut client = Client::connect(addr).await?;

    // Flush all data to ensure clean environment
    let flush_resp = client.send_command_str("FLUSHALL", &[]).await?;
    assert_eq!(flush_resp, RespValue::SimpleString("OK".to_string()));

    println!("Testing Redis Streams functionality...");

    // ======== TEST XADD COMMAND ========
    println!("Testing XADD command");

    // Test XADD with autogenerated ID
    // Format: XADD key ID field value [field value ...]
    let xadd_result = client
        .send_command_str(
            "XADD",
            &[
                "mystream",
                "*", // Autogenerate ID
                "sensor-id",
                "1234",
                "temperature",
                "19.8",
                "humidity",
                "0.23",
            ],
        )
        .await?;

    let entry_id = match xadd_result {
        RespValue::BulkString(Some(id_bytes)) => {
            let id = String::from_utf8(id_bytes.clone())?;
            println!("Entry ID: {}", id);

            // ID should be in format "timestamp-sequence"
            assert!(
                id.contains("-"),
                "Stream entry ID should be in format timestamp-sequence"
            );
            id
        }
        RespValue::Error(ref err) => {
            if err.contains("unknown command") || err.contains("not implemented") {
                println!("XADD command is not implemented, skipping remaining Stream tests");
                return Ok(());
            } else {
                panic!("Unexpected error response from XADD: {:?}", xadd_result);
            }
        }
        _ => {
            panic!("Unexpected response type from XADD: {:?}", xadd_result);
        }
    };

    // Add a few more entries with different data
    let xadd_result2 = client
        .send_command_str(
            "XADD",
            &[
                "mystream",
                "*",
                "sensor-id",
                "1234",
                "temperature",
                "20.1",
                "humidity",
                "0.25",
            ],
        )
        .await?;

    let entry_id2 = if let RespValue::BulkString(Some(id_bytes)) = xadd_result2 {
        String::from_utf8(id_bytes)?
    } else {
        panic!("Unexpected response type from XADD: {:?}", xadd_result2);
    };

    let xadd_result3 = client
        .send_command_str(
            "XADD",
            &[
                "mystream",
                "*",
                "sensor-id",
                "5678",
                "temperature",
                "22.4",
                "humidity",
                "0.18",
            ],
        )
        .await?;

    let entry_id3 = if let RespValue::BulkString(Some(id_bytes)) = xadd_result3 {
        String::from_utf8(id_bytes)?
    } else {
        panic!("Unexpected response type from XADD: {:?}", xadd_result3);
    };

    // ======== TEST XLEN COMMAND ========
    println!("Testing XLEN command");

    // Test XLEN to get stream length
    let xlen_result = client.send_command_str("XLEN", &["mystream"]).await?;
    match xlen_result {
        RespValue::Integer(len) => {
            assert_eq!(len, 3, "XLEN should return 3 for stream with 3 entries");
        }
        RespValue::Error(ref err) => {
            if err.contains("unknown command") || err.contains("not implemented") {
                println!("XLEN command is not implemented, skipping XLEN tests");
            } else {
                panic!("Unexpected error response from XLEN: {:?}", xlen_result);
            }
        }
        _ => {
            panic!("Unexpected response type from XLEN: {:?}", xlen_result);
        }
    }

    // ======== TEST XRANGE COMMAND ========
    println!("Testing XRANGE command");

    // Test XRANGE to get a range of stream entries
    let xrange_result = client
        .send_command_str("XRANGE", &["mystream", "-", "+"])
        .await?;
    match xrange_result {
        RespValue::Array(Some(entries)) => {
            assert_eq!(entries.len(), 3, "XRANGE should return 3 entries");

            // Verify format of first entry
            if let RespValue::Array(Some(entry_parts)) = &entries[0] {
                assert_eq!(
                    entry_parts.len(),
                    2,
                    "Entry should have ID and fields array"
                );

                // First part should be the ID
                if let RespValue::BulkString(Some(id_bytes)) = &entry_parts[0] {
                    let id = String::from_utf8(id_bytes.clone())?;
                    assert_eq!(id, entry_id, "First entry ID should match");
                } else {
                    panic!("Expected BulkString for entry ID");
                }

                // Second part should be an array of field-value pairs
                if let RespValue::Array(Some(fields)) = &entry_parts[1] {
                    assert_eq!(
                        fields.len(),
                        6,
                        "Entry should have 3 field-value pairs (6 elements total)"
                    );

                    // Verify field-value pairs
                    let mut found_sensor_id = false;
                    let mut found_temperature = false;
                    let mut found_humidity = false;

                    for i in (0..fields.len()).step_by(2) {
                        if let RespValue::BulkString(Some(field_bytes)) = &fields[i] {
                            let field = String::from_utf8(field_bytes.clone())?;
                            let value =
                                if let RespValue::BulkString(Some(value_bytes)) = &fields[i + 1] {
                                    String::from_utf8(value_bytes.clone())?
                                } else {
                                    panic!("Expected BulkString for field value");
                                };

                            if field == "sensor-id" {
                                assert_eq!(value, "1234", "sensor-id should be 1234");
                                found_sensor_id = true;
                            } else if field == "temperature" {
                                assert_eq!(value, "19.8", "temperature should be 19.8");
                                found_temperature = true;
                            } else if field == "humidity" {
                                assert_eq!(value, "0.23", "humidity should be 0.23");
                                found_humidity = true;
                            }
                        } else {
                            panic!("Expected BulkString for field name");
                        }
                    }

                    assert!(found_sensor_id, "Entry should have sensor-id field");
                    assert!(found_temperature, "Entry should have temperature field");
                    assert!(found_humidity, "Entry should have humidity field");
                } else {
                    panic!("Expected Array for fields");
                }
            } else {
                panic!("Expected Array for stream entry");
            }
        }
        RespValue::Error(ref err) => {
            if err.contains("unknown command") || err.contains("not implemented") {
                println!("XRANGE command is not implemented, skipping XRANGE tests");
            } else {
                panic!("Unexpected error response from XRANGE: {:?}", xrange_result);
            }
        }
        _ => {
            panic!("Unexpected response type from XRANGE: {:?}", xrange_result);
        }
    }

    // Test XRANGE with COUNT option
    let xrange_count_result = client
        .send_command_str("XRANGE", &["mystream", "-", "+", "COUNT", "2"])
        .await?;
    match xrange_count_result {
        RespValue::Array(Some(entries)) => {
            assert_eq!(
                entries.len(),
                2,
                "XRANGE with COUNT should return 2 entries"
            );
        }
        RespValue::Error(_) => {
            println!("XRANGE with COUNT option may not be implemented, skipping test");
        }
        _ => {
            panic!(
                "Unexpected response type from XRANGE with COUNT: {:?}",
                xrange_count_result
            );
        }
    }

    // ======== TEST XREAD COMMAND ========
    println!("Testing XREAD command");

    // Test XREAD to get entries newer than a specific ID
    let xread_result = client
        .send_command_str("XREAD", &["STREAMS", "mystream", &entry_id2])
        .await?;
    match xread_result {
        RespValue::Array(Some(results)) => {
            assert_eq!(results.len(), 1, "XREAD should return results for 1 stream");

            // First element should be an array with stream name and entries
            if let RespValue::Array(Some(stream_data)) = &results[0] {
                assert_eq!(
                    stream_data.len(),
                    2,
                    "Stream data should have name and entries"
                );

                // First element should be the stream name
                if let RespValue::BulkString(Some(name_bytes)) = &stream_data[0] {
                    assert_eq!(
                        std::str::from_utf8(name_bytes)?,
                        "mystream",
                        "Stream name should be 'mystream'"
                    );
                } else {
                    panic!("Expected BulkString for stream name");
                }

                // Second element should be an array of entries
                if let RespValue::Array(Some(entries)) = &stream_data[1] {
                    assert_eq!(
                        entries.len(),
                        1,
                        "Should have 1 entry after the specified ID"
                    );

                    // Verify entry format
                    if let RespValue::Array(Some(entry_parts)) = &entries[0] {
                        // First part should be the ID
                        if let RespValue::BulkString(Some(id_bytes)) = &entry_parts[0] {
                            assert_eq!(
                                String::from_utf8(id_bytes.clone())?,
                                entry_id3,
                                "Entry ID should match third entry"
                            );
                        } else {
                            panic!("Expected BulkString for entry ID");
                        }
                    } else {
                        panic!("Expected Array for entry");
                    }
                } else {
                    panic!("Expected Array for entries");
                }
            } else {
                panic!("Expected Array for stream data");
            }
        }
        RespValue::Error(ref err) => {
            if err.contains("unknown command") || err.contains("not implemented") {
                println!("XREAD command is not implemented, skipping XREAD tests");
            } else {
                panic!("Unexpected error response from XREAD: {:?}", xread_result);
            }
        }
        RespValue::BulkString(None) => {
            // This could happen if there are no entries after the specified ID
            panic!("XREAD returned nil, but there should be entries after the specified ID");
        }
        _ => {
            panic!("Unexpected response type from XREAD: {:?}", xread_result);
        }
    }

    // ======== TEST XDEL COMMAND ========
    println!("Testing XDEL command");

    // Test XDEL to delete a stream entry
    let xdel_result = client
        .send_command_str("XDEL", &["mystream", &entry_id])
        .await?;
    match xdel_result {
        RespValue::Integer(count) => {
            assert_eq!(count, 1, "XDEL should return 1 (count of deleted entries)");

            // Verify entry was deleted using XRANGE
            let xrange_after_del = client
                .send_command_str("XRANGE", &["mystream", "-", "+"])
                .await?;
            if let RespValue::Array(Some(entries)) = xrange_after_del {
                assert_eq!(
                    entries.len(),
                    2,
                    "XRANGE should return 2 entries after deletion"
                );

                // Check that the deleted ID is no longer present
                for entry in entries {
                    if let RespValue::Array(Some(entry_parts)) = entry
                        && let RespValue::BulkString(Some(id_bytes)) = &entry_parts[0]
                    {
                        let id = String::from_utf8(id_bytes.clone())?;
                        assert_ne!(id, entry_id, "Deleted entry ID should not be present");
                    }
                }
            }
        }
        RespValue::Error(ref err) => {
            if err.contains("unknown command") || err.contains("not implemented") {
                println!("XDEL command is not implemented, skipping XDEL tests");
            } else {
                panic!("Unexpected error response from XDEL: {:?}", xdel_result);
            }
        }
        _ => {
            panic!("Unexpected response type from XDEL: {:?}", xdel_result);
        }
    }

    // ======== TEST XTRIM COMMAND ========
    println!("Testing XTRIM command");

    // Add more entries to have enough for trimming
    for _ in 0..10 {
        client
            .send_command_str(
                "XADD",
                &[
                    "mystream",
                    "*",
                    "sensor-id",
                    "9999",
                    "temperature",
                    "25.0",
                    "humidity",
                    "0.30",
                ],
            )
            .await?;
    }

    // Test XTRIM to limit stream length
    let xtrim_result = client
        .send_command_str("XTRIM", &["mystream", "MAXLEN", "5"])
        .await?;
    match xtrim_result {
        RespValue::Integer(count) => {
            assert!(
                count > 0,
                "XTRIM should return count of removed entries (>0)"
            );

            // Verify stream length after trim using XLEN
            let xlen_after_trim = client.send_command_str("XLEN", &["mystream"]).await?;
            if let RespValue::Integer(len) = xlen_after_trim {
                assert!(len <= 5, "Stream length should be <= 5 after XTRIM");
            }
        }
        RespValue::Error(ref err) => {
            if err.contains("unknown command") || err.contains("not implemented") {
                println!("XTRIM command is not implemented, skipping XTRIM tests");
            } else {
                panic!("Unexpected error response from XTRIM: {:?}", xtrim_result);
            }
        }
        _ => {
            panic!("Unexpected response type from XTRIM: {:?}", xtrim_result);
        }
    }

    // ======== TEST CONSUMER GROUPS ========
    println!("Testing consumer groups");

    // Create a stream for consumer group testing
    client
        .send_command_str("XADD", &["groupstream", "*", "field", "value1"])
        .await?;
    client
        .send_command_str("XADD", &["groupstream", "*", "field", "value2"])
        .await?;
    client
        .send_command_str("XADD", &["groupstream", "*", "field", "value3"])
        .await?;

    // Test XGROUP CREATE to create a consumer group
    let xgroup_create_result = client
        .send_command_str("XGROUP", &["CREATE", "groupstream", "mygroup", "0"])
        .await?;
    match xgroup_create_result {
        RespValue::SimpleString(response) => {
            assert_eq!(response, "OK", "XGROUP CREATE should return OK");

            // Test XREADGROUP to read from a consumer group
            let xreadgroup_result = client
                .send_command_str(
                    "XREADGROUP",
                    &[
                        "GROUP",
                        "mygroup",
                        "consumer1",
                        "STREAMS",
                        "groupstream",
                        ">",
                    ],
                )
                .await?;

            if let RespValue::Array(Some(results)) = xreadgroup_result {
                // Verify XREADGROUP results
                assert_eq!(
                    results.len(),
                    1,
                    "XREADGROUP should return results for 1 stream"
                );

                if let RespValue::Array(Some(stream_data)) = &results[0]
                    && let RespValue::Array(Some(entries)) = &stream_data[1]
                {
                    assert_eq!(entries.len(), 3, "XREADGROUP should return all 3 entries");
                }

                // Test XACK to acknowledge a message
                if let RespValue::Array(Some(stream_data)) = &results[0]
                    && let RespValue::Array(Some(entries)) = &stream_data[1]
                    && let RespValue::Array(Some(entry_parts)) = &entries[0]
                    && let RespValue::BulkString(Some(id_bytes)) = &entry_parts[0]
                {
                    let id = String::from_utf8(id_bytes.clone())?;

                    let xack_result = client
                        .send_command_str("XACK", &["groupstream", "mygroup", &id])
                        .await?;
                    if let RespValue::Integer(count) = xack_result {
                        assert_eq!(
                            count, 1,
                            "XACK should return 1 for one acknowledged message"
                        );
                    } else if let RespValue::Error(err) = &xack_result {
                        if err.contains("unknown command") || err.contains("not implemented") {
                            println!("XACK command is not implemented, skipping");
                        } else {
                            panic!("Unexpected error response from XACK: {:?}", xack_result);
                        }
                    } else {
                        panic!("Unexpected response type from XACK: {:?}", xack_result);
                    }
                }
            } else if let RespValue::Error(err) = &xreadgroup_result {
                if err.contains("unknown command") || err.contains("not implemented") {
                    println!("XREADGROUP command is not implemented, skipping");
                } else {
                    panic!(
                        "Unexpected error response from XREADGROUP: {:?}",
                        xreadgroup_result
                    );
                }
            } else {
                panic!(
                    "Unexpected response type from XREADGROUP: {:?}",
                    xreadgroup_result
                );
            }
        }
        RespValue::Error(ref err) => {
            if err.contains("unknown command") || err.contains("not implemented") {
                println!("XGROUP CREATE command is not implemented, skipping consumer group tests");
            } else {
                panic!(
                    "Unexpected error response from XGROUP CREATE: {:?}",
                    xgroup_create_result
                );
            }
        }
        _ => {
            panic!(
                "Unexpected response type from XGROUP CREATE: {:?}",
                xgroup_create_result
            );
        }
    }

    // ======== TEST INTERACTION WITH OTHER COMMANDS ========
    println!("Testing interaction with other Redis commands");

    // Test TYPE detection for stream
    let type_result = client.send_command_str("TYPE", &["mystream"]).await?;
    assert!(
        matches!(type_result, RespValue::SimpleString(ref s) if s == "stream"),
        "TYPE for stream should return 'stream'"
    );

    // Test DEL on stream
    let del_result = client.send_command_str("DEL", &["mystream"]).await?;
    assert_eq!(
        del_result,
        RespValue::Integer(1),
        "DEL should return 1 for deleting the stream"
    );

    // Verify stream is gone
    let exists_result = client.send_command_str("EXISTS", &["mystream"]).await?;
    assert_eq!(
        exists_result,
        RespValue::Integer(0),
        "Stream should be deleted"
    );

    println!("All Stream tests passed!");
    Ok(())
}
